on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: print readme
        run: cat ./readme.md
      - name: check localhost
        run: curl localhost:5173
